name: vb1980 kvr

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to compile'
        options:
        - MSG1500-7615
        - R6220
        - K2P
        default: 'MSG1500-7615'
      plugins:
        description: 'json format string of include configs'
        required: true
        default: '{"aria":"n","transmission":"n","vpnsvr":"n","vpncli":"n","vpncmd":"n","ss":"n","v2ray":"n","xray":"n","trojan":"n","ssobfs":"n","dnsforwarder":"n","adbyby":"n","adguardhome":"n","smartdns":"n","aliddns":"n","zerotier":"n","ddnsto":"n","wireguard":"n","frpc":"n","aldriver":"n","mentohust":"n","scutclient":"n","njitclient":"n","minieap":"n","dogcom":"n"}'
      firmwarever:
        description: 'firmware''s version'
        required: true
        default: '202302'
      uploadwet:
        type: boolean
        description: 'upload firmware to wetransfer'
        required: false
        default: 'false'

      upload_release:
        type: boolean
        description: 'upload firmware to RELEASE'
        required: false
        default: 'false'
env:
  REPOSITORY_URL: https://github.com/vb1980/Padavan-KVR.git
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/rt-n56u
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_DATEPREFIX: $(date +"%Y%m%d")
  FIRMWARE_AUTHOR: vb1980
  FIRMWARE_PATH: /opt/firmwares
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH/toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget $TOOLCHAIN_URL
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x

    - name: Parse json string of include plugins
      run: |
        echo "aria=${{fromJson(github.event.inputs.plugins).aria}}" >> $GITHUB_ENV
        echo "transmission=${{fromJson(github.event.inputs.plugins).transmission}}" >> $GITHUB_ENV
        echo "vpnsvr=${{fromJson(github.event.inputs.plugins).vpnsvr}}" >> $GITHUB_ENV
        echo "vpncli=${{fromJson(github.event.inputs.plugins).vpncli}}" >> $GITHUB_ENV
        echo "vpncmd=${{fromJson(github.event.inputs.plugins).vpncmd}}" >> $GITHUB_ENV
        echo "ss=${{fromJson(github.event.inputs.plugins).ss}}" >> $GITHUB_ENV
        echo "v2ray=${{fromJson(github.event.inputs.plugins).v2ray}}" >> $GITHUB_ENV
        echo "xray=${{fromJson(github.event.inputs.plugins).xray}}" >> $GITHUB_ENV
        echo "trojan=${{fromJson(github.event.inputs.plugins).trojan}}" >> $GITHUB_ENV
        echo "ssobfs=${{fromJson(github.event.inputs.plugins).ssobfs}}" >> $GITHUB_ENV
        echo "dnsforwarder=${{fromJson(github.event.inputs.plugins).dnsforwarder}}" >> $GITHUB_ENV
        echo "adbyby=${{fromJson(github.event.inputs.plugins).adbyby}}" >> $GITHUB_ENV
        echo "adguardhome=${{fromJson(github.event.inputs.plugins).adguardhome}}" >> $GITHUB_ENV
        echo "smartdns=${{fromJson(github.event.inputs.plugins).smartdns}}" >> $GITHUB_ENV
        echo "aliddns=${{fromJson(github.event.inputs.plugins).aliddns}}" >> $GITHUB_ENV
        echo "zerotier=${{fromJson(github.event.inputs.plugins).zerotier}}" >> $GITHUB_ENV
        echo "ddnsto=${{fromJson(github.event.inputs.plugins).ddnsto}}" >> $GITHUB_ENV
        echo "wireguard=${{fromJson(github.event.inputs.plugins).wireguard}}" >> $GITHUB_ENV
        echo "frpc=${{fromJson(github.event.inputs.plugins).frpc}}" >> $GITHUB_ENV
        echo "aldriver=${{fromJson(github.event.inputs.plugins).aldriver}}" >> $GITHUB_ENV
        echo "mentohust=${{fromJson(github.event.inputs.plugins).mentohust}}" >> $GITHUB_ENV
        echo "scutclient=${{fromJson(github.event.inputs.plugins).scutclient}}" >> $GITHUB_ENV
        echo "njitclient=${{fromJson(github.event.inputs.plugins).njitclient}}" >> $GITHUB_ENV
        echo "minieap=${{fromJson(github.event.inputs.plugins).minieap}}" >> $GITHUB_ENV
        echo "dogcom=${{fromJson(github.event.inputs.plugins).dogcom}}" >> $GITHUB_ENV
    - name: Custom config
      run: |
        cd $WORK_PATH/trunk
        if [ ! -f configs/templates/${{ github.event.inputs.target }}.config ] ; then
        echo "configs/templates/${{ github.event.inputs.target }}.config not found"
        exit 1
        fi
        cp -f configs/templates/${{ github.event.inputs.target }}.config .config
        ################################################################################################
        #å› ä¸åŒåž‹å·é…ç½®åŠŸèƒ½ä¸ä¸€æ ·ï¼Œæ‰€ä»¥å…ˆæŠŠé…ç½®é¡¹åˆ é™¤ï¼Œå¦‚æžœä½ è‡ªå·±è¦æ·»åŠ å…¶ä»–çš„ï¼Œä¹Ÿè¦å†™ä¸Šåˆ é™¤è¿™ä¸€æ¡ï¼Œåˆ‡è®°ï¼ï¼ï¼
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN   
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #åˆ é™¤é…ç½®é¡¹SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #åˆ é™¤é…ç½®é¡¹SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #åˆ é™¤é…ç½®é¡¹DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #åˆ é™¤é…ç½®é¡¹FRP Client
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #åˆ é™¤é…ç½®é¡¹FRPS Server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NPC/d' .config #åˆ é™¤é…ç½®é¡¹NPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #åˆ é™¤é…ç½®é¡¹TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #åˆ é™¤é…ç½®é¡¹é˜¿é‡ŒDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #åˆ é™¤é…ç½®é¡¹ZEROTIER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CLOUDFLAREDDNS/d' .config #åˆ é™¤é…ç½®é¡¹CLOUDFLAREDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NVPPROXY/d' .config #åˆ é™¤é…ç½®é¡¹NVPPROXY
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DDNSTO/d' .config #åˆ é™¤é…ç½®é¡¹DDNSTO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config #åˆ é™¤é…ç½®é¡¹WIREGUARD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MICROSOCKS/d' .config
        #ä¸‹è½½åŠŸèƒ½
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #åˆ é™¤é…ç½®é¡¹aria
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config #åˆ é™¤é…ç½®é¡¹ariaç½‘é¡µæŽ§åˆ¶å°
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config #åˆ é™¤é…ç½®é¡¹TRANSMISSION
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config #åˆ é™¤é…ç½®é¡¹TRANSMISSIONç½‘é¡µæŽ§åˆ¶å°
        #æ ¡å›­ç½‘ç›¸å…³å¼€å§‹
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #åˆ é™¤é…ç½®é¡¹MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        #æ ¡å›­ç½‘ç›¸å…³ç»“æŸ
        ######################################################################
        #ä»¥ä¸‹é€‰é¡¹æ˜¯å®šä¹‰ä½ éœ€è¦çš„åŠŸèƒ½ï¼ˆy=é›†æˆ,n=å¿½ç•¥ï¼‰ï¼Œé‡æ–°å†™å…¥åˆ°.configæ–‡ä»¶
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD_SYSLOG=n"  >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD=n"  >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD36=n"  >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n"  >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_U2EC=n"  >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_LPRD=n"  >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=${{env.vpnsvr}}" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=${{env.vpncli}}" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=${{env.vpncmd}}" >> .config #SOFTETHERVPN
        #ç§‘å­¦ç›¸å…³
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=${{env.ss}}" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=${{env.v2ray}}" >> .config #é›†æˆv2rayæ‰§è¡Œæ–‡ä»¶ï¼ˆ3.8Må·¦å³)
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=${{env.xray}}" >> .config #é›†æˆxrayæ‰§è¡Œæ–‡ä»¶(5.6Må·¦å³)ï¼Œå¯ä»¥ä»£æ›¿v2rayï¼Œæ³¨ï¼šå¦‚æžœé—ªå­˜å¤ªå°ä¸å¤Ÿè¿˜æ˜¯å»ºè®®ä½¿ç”¨v2ray
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=${{env.trojan}}" >> .config #é›†æˆtrojanæ‰§è¡Œæ–‡ä»¶(1.1Må·¦å³)
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=${{env.ssobfs}}" >> .config # simple-obfsæ··æ·†æ’ä»¶
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config #socks5
        #
        echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #å¯ä»¥ä¸é›†æˆ
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=${{env.dnsforwarder}}" >> .config #DNSFORWARDER
        #
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=${{env.frpc}}" >> .config #å†…ç½‘ç©¿é€FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #å†…ç½‘ç©¿é€FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_NPC=n" >> .config #åˆ é™¤é…ç½®é¡¹NPC
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=${{env.adbyby}}" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KPå¹¿å‘Šè¿‡æ»¤
        #
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=${{env.smartdns}}" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdnsäºŒè¿›åˆ¶æ–‡ä»¶
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=${{env.adguardhome}}" >> .config
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=${{env.aliddns}}" >> .config #é˜¿é‡ŒDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=${{env.zerotier}}" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_CLOUDFLAREDDNS=n" >> .config #CLOUDFLAREDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_NVPPROXY=n" >> .config #NVPPROXY
        echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=${{env.ddnsto}}" >> .config #DDNSTO
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=${{env.wireguard}}" >> .config #WIREGUARD
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=${{env.aldriver}}" >> .config #é˜¿é‡Œäº‘ç›˜
        #
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #åœ¨çº¿æ–‡ä»¶ç®¡ç†æœåŠ¡
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #é›†æˆcadduæ‰§è¡Œæ–‡ä»¶ï¼Œæ­¤æ–‡ä»¶æœ‰13M,è¯·æ³¨æ„å›ºä»¶å¤§å°ã€‚å¦‚æžœä¸é›†æˆï¼Œä¼šä»Žç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        #
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #ç½‘æ˜“äº‘è§£é”
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #ç½‘æ˜“äº‘è§£é”GOç‰ˆæœ¬æ‰§è¡Œæ–‡ä»¶ï¼ˆ4Må¤šï¼‰æ³¨æ„å›ºä»¶è¶…å¤§å°,ä¸é›†æˆä¼šè‡ªåŠ¨ä¸‹è½½
        #ä¸‹è½½åŠŸèƒ½
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=${{env.aria}}" >> .config #é…ç½®é¡¹aria
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=${{env.aria}}" >> .config #é…ç½®é¡¹ariaç½‘é¡µæŽ§åˆ¶å°
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=${{env.transmission}}" >> .config #åˆ é™¤é…ç½®é¡¹TRANSMISSION
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=${{env.transmission}}" >> .config #é…ç½®é¡¹TRANSMISSIONç½‘é¡µæŽ§åˆ¶å°
        #æ ¡å›­ç½‘ç›¸å…³å¼€å§‹
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=${{env.mentohust}}" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=${{env.scutclient}}" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=${{env.njitclient}}" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=${{env.minieap}}" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=${{env.dogcom}}" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        #æ ¡å›­ç½‘ç›¸å…³ç»“æŸ
        #########################################################################################
        #è‡ªå®šä¹‰æ·»åŠ å…¶å®ƒåŠŸèƒ½è¯·å‚è€ƒæºç configs/templates/ç›®å½•ä¸‹çš„configæ–‡ä»¶ã€‚æŒ‰ç…§ä¸Šé¢çš„æ ¼å¼æ·»åŠ å³å¯
        #æ ¼å¼å¦‚ä¸‹ï¼š
        #sed -i '/è‡ªå®šä¹‰é¡¹/d' .config
        #echo "è‡ªå®šä¹‰é¡¹=y" >> .config
        sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${{ github.event.inputs.firmwarever }}/g" ./versions.inc
        echo 'æ›´æ–°ç‰ˆæœ¬å·æ—¶é—´'
        #########################################################################################
    - name: Build firmware
      run: |
        cd $WORK_PATH/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify ${{ github.event.inputs.target }} 0
        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: Organize firmware files
      id: organize
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $WORK_PATH/trunk/images
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_AUTHOR}"_"$firmwarefile
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success'
      with:
        name: Padavan-${{ github.event.inputs.target }}-KVR
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to WeTransfer
      if: steps.organize.outputs.status == 'success' && github.event.inputs.uploadwet == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "url=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
     
    - name: Generate release tag
      id: tag
      if: steps.organize.outputs.status == 'success' && github.event.inputs.upload_release == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")-Padavan4.4-${{ github.event.inputs.target }}" >> $GITHUB_OUTPUT
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "ðŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "ðŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*     
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 7
        keep_minimum_runs: 4
    
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      if: github.event.inputs.upload_release == 'true' && !cancelled()
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove obsolete firmwares on artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      if: steps.organizer.outputs.status == 'success'
      with:
        age: '1 day'
        skip-recent: 5
